package com.linkedin.java9demo.impl.internal;

import com.linkedin.java9demo.api.SomeApi;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library implements SomeApi {
    public boolean someLibraryMethod() {
        return true;
    }
}
